### ISSUE TITLE
va lo streaming ma non il download

### ISSUE THREAD

**Issue by artifix100** [Bbalduzz/stream-buddy#2]
ottimo lavoro grazie , tuttavia a me va lo streaming ma non il download di qualsiasi contenuto , mi risulta questo errore : 

PS C:\Users\piern\Downloads\stream-buddy-main> python main.py
C:\Users\piern\Downloads\stream-buddy-main\main.py:114: SyntaxWarning: invalid escape sequence '\_'
  '''
      
         _____ __                            ____            __    __     
        / ___// /_________  ____ _____ ___  / __ )__  ______/ /___/ /_  __
        \__ \/ __/ ___/ _ \/ __ `/ __ `__ \/ __  / / / / __  / __  / / / /
       ___/ / /_/ /  /  __/ /_/ / / / / / / /_/ / /_/ / /_/ / /_/ / /_/ / 
      /____/\__/_/   \___/\__,_/_/ /_/ /_/_____/\__,_/\__,_/\__,_/\__, / 
      .cz                                                        /____/ 

[?] Che cosa vuoi guardare?: oppenheimer
[?] Seleziona un contenuto: | Oppenheimer [ Movie ][ 8.3 ][ 2023-07-19 ]        
 > | Oppenheimer [ Movie ][ 8.3 ][ 2023-07-19 ]

[?] Seleziona la qualità desiderata: 720p                                       
 > 720p
   480p

[?] Cosa vuoi fare:
 > [X] download
   [ ] watch

  0%|                                                 | 0/2706 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\piern\Downloads\stream-buddy-main\main.py", line 287, in <module>
    main()
  File "C:\Users\piern\Downloads\stream-buddy-main\main.py", line 285, in main  
    actions_map.get(tuple(sorted(action)), lambda: None)()
  File "C:\Users\piern\Downloads\stream-buddy-main\main.py", line 147, in <lambda>
    (0,): lambda: perform_download(media, quality_index),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\Downloads\stream-buddy-main\main.py", line 160, in perform_download
    VideoDownloader().download(download_options)
  File "C:\Users\piern\Downloads\stream-buddy-main\src\downloader.py", line 87, in download
    ts_files = list(tqdm(executor.map(self.download_and_decrypt, urls), total=len(urls)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\piern\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piern\Downloads\stream-buddy-main\src\downloader.py", line 53, in download_and_decrypt
    self.video_decoder.decrypt_ts_file(temp_filename, f"dec_temp_ts/{output_filename}")
  File "C:\Users\piern\Downloads\stream-buddy-main\src\downloader.py", line 16, in decrypt_ts_file
    with open(input_filename, 'rb') as infile, open(output_filename, 'wb') as outfile:
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dec_temp_ts/0000-0250.ts'
PS C:\Users\piern\Downloads\stream-buddy-main>

**Comment by Bbalduzz** [comment]
ciao, non sto seguendo più questa repo. Usa questo https://streambuddy.onrender.com/

**Comment by artifix100** [comment]
ciao intanto grazie della risposta , sembra meraviglioso ma come funziona ? cioè io faccio ricerca arrivano le belle anteprime come figurine ma poi se clicco sopra nulla accade , dove faccio la scemenza ? ciao

**Comment by Bbalduzz** [comment]
ciao, no no non stai sbagliando nulla, ma se controlli nell'angolo basso a destra c'e' un freccetta che ruota. Sta a significare che si sta generando il token per visualizzare i contenuti. Successivamente si aprira' una piccola finestra, li saprai che potrai guardare quello che vuoi

P.S. se usi firefox il player ha ancora qualche problema: se non parte il contenuto ricarica la pagina fino a che non vedi che si e' caricato , poi premi play ;)

**Comment by artifix100** [comment]
ok non so perché ma funziona solo con navigazione in incognito comunque eccellente , ultimo problema : le serie come si fa a scegliere tra episodi ? io ad esempio nella serie Grandi Speranze è segnato 6 episodi ma cliccando sopra mi si apre sempre e solo il primo ah ah

**Comment by Bbalduzz** [comment]
si, è normale, gli episodi e le season si cambiano direttamente dal player.

https://github.com/Bbalduzz/stream-buddy/assets/81587335/ed809a4b-e7e5-4167-8de3-9794b31ce742

**Comment by artifix100** [comment]
Ciao scusa , stream buddy ( il link che mi hai passato ) non va più con nessun browser ho provato con google in incognito ma nulla non si apre nessuna finestra nemmeno accenna ad aprirsi . capita solo a me o hanno fatto qualche intervento ?

**Comment by Bbalduzz** [comment]
Ciao, il sito si apre, il player invece no. Sono al corrente della problematica, causata dall'interruzione di un serivizio utilizzato nella creazione dei token.
So risolvendo.

**Comment by artifix100** [comment]
Sì è cosi come dici,  in effetti non mi sono spiegato bene😃 grazie della sollecita risposta ti auguro buon lavoro.  
--
Inviato da Libero Mail

**Comment by artifix100** [comment]
Ciao scusa volevo poi chiederti : è possibile effettuare lo streaming direttamente dal chromecast della TV?   
   
   
    Il 12/01/2024 16:56 CET Edoardo Balducci ***@***.***> ha scritto:
    
   
     
    
   
     
    
     
   Ciao, il sito si apre, il player invece no. Sono al corrente della problematica, causata dall'interruzione di un serivizio utilizzato nella creazione dei token.So risolvendo.

**Comment by Bbalduzz** [comment]
ciao, no, non ho ancora aggiunto il supporto per le TV. 
Per ora ho solo sistemato il problema dei giorni passati

**Comment by artifix100** [comment]
Si visto che da browser funziona di nuovo anzi meglio di prima grazie. Già così é un grande strumento,  con supporto tv sarebbe incredibile. In caso grazie davvero.  
--
Inviato da Libero Mail

**Comment by Bbalduzz** [comment]
Ciao, ho aggiunto il supporto a Airplay (nei browser che lo supportano ex. Safari)
Per qunato riguarda chromecast puoi farlo direttamente da Chrome.
tre pallini in alto a destra > Save ans Share > Cast.

Il player ha ancora qualche problema di cui faccio fatica ad identificare la causa, nel prossimo periodo cercherò di fixare tutto.

**Comment by artifix100** [comment]
Ciao intanto ti ringrazio davvero, ieri sera sono riuscito a vedere un film direttamente dal browser di chromecast ed è stato godibilissimo. Però poco fa mi sembra sia stato di nuovo bloccato il player. Non compare più.  Spero sia risolvibile : é qualcuno che mette il bastone tra le ruote o sono problemi normali? 😃 ciao e grazie in ogni caso.  
--
Inviato da Libero Mail

**Comment by artifix100** [comment]
Ciao si direi che il player ha sempre difficoltà a partire,  da ogni device al momento ciao la comunicazione non è per metterti fretta ci mancherebbe avrai altre cose da fare, è solo per informazione.  Grazie comunque.  
   
   
    Il 16/01/2024 08:15 CET Edoardo Balducci ***@***.***> ha scritto:
    
   
     
    
   
     
    
     
   Ciao, ho aggiunto il supporto a Airplay (nei browser che lo supportano ex. Safari)Per qunato riguarda chromecast puoi farlo direttamente da Chrome.tre pallini in alto a destra > Save ans Share > Cast. 
   Il player ha ancora qualche problema di cui faccio fatica ad identificare la causa, nel prossimo periodo cercherò di fixare tutto.

**Comment by artifix100** [comment]
da quel che ho capito non si connette 

During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "C:\Users\Novelli\Downloads\stream-buddy-main (1)\stream-buddy-main\main.py", line 287, in <module>
main()
File "C:\Users\Novelli\Downloads\stream-buddy-main (1)\stream-buddy-main\main.py", line 123, in main
search_instance.search()
File "C:\Users\Novelli\Downloads\stream-buddy-main (1)\stream-buddy-main\main.py", line 18, in search
api_response = requests.get(f"https://streamingcommunity.{DOMAIN}/api/search?q={self.query}").json()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
return request("get", url, params=params, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 553, in send
raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='streamingcommunity.cz', port=443): Max retries exceeded with url: /api/search?q=Napoleon (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object
at 0x000002029834CC10>, 'Connection to streamingcommunity.cz timed out. (connect timeout=None)'))

**Comment by Bbalduzz** [comment]
Ciao!
Per quanto riguarda lo script, basta che aggiorni il domain in `confing.ini`, il nuovo dominio e' `estate`, comunque controlla con il bot ufficiale di streamingcommunity

```
[DOMAIN]
updated = estate
```

Per quanto riguarda il sito hanno aggiornato molte cose e hanno introdotto nuovi blocchi, e ho paura che continuando ad aggiornare il sito stando dietro a questi upgrade finisca in un blocco totale, quindi non so se, in che misura, e quando tornera' up, magari lo terro' ma con il limite del 720p

**Comment by artifix100** [comment]
ciao non andando più il sito onrender non è più possibile scaricare il file mp4 per vederlo offline . e nello script se si seleziona [ ] download immancabilmente si interrompe dopo aver scaricato un po' di file ts  ti allego report , c'è soluzione per avere un file da vedere offline ? grazie 

PS C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main> python main.py

                                                                         _____ __                            ____            __    __     
                                                                        / ___// /_________  ____ _____ ___  / __ )__  ______/ /___/ /_  __
                                                                        \__ \/ __/ ___/ _ \/ __ `/ __ `__ \/ __  / / / / __  / __  / / / /
                                                                       ___/ / /_/ /  /  __/ /_/ / / / / / / /_/ / /_/ / /_/ / /_/ / /_/ / 
                                                                      /____/\__/_/   \___/\__,_/_/ /_/ /_/_____/\__,_/\__,_/\__,_/\__, /  
                                                                      .estate                                                    /____/   

[?] Che cosa vuoi guardare?: troy
[?] Seleziona un contenuto: | Troy - La caduta di Troia              [ TV Series ][ 6.3 ][            ]
   | Troy                                   [ Movie     ][ 7.7 ][ 2004-05-03 ]
 > | Troy - La caduta di Troia              [ TV Series ][ 6.3 ][            ]
   | Green Zone                             [ Movie     ][ 7.3 ][ 2010-03-11 ]
   | Little Nicky - Un diavolo a Manhattan  [ Movie     ][ 6.1 ][ 2000-11-10 ]
   | Crank                                  [ Movie     ][ 6.8 ][ 2006-08-31 ]
   | The Idol                               [ TV Series ][ 5.4 ][            ]
   | The Other Side                         [ Movie     ][ 7.2 ][ 2020-10-23 ]
   | Scherzi mortali                        [ Movie     ][ 3.9 ][            ]
   | The Nest (Il nido)                     [ Movie     ][ 7.0 ][ 2019-08-15 ]
   | Dash & Lily                            [ TV Series ][ 8.0 ][            ]
   | Il tagliaerbe                          [ Movie     ][ 5.5 ][            ]
   | I Goldbergs                            [ TV Series ][ 8.2 ][            ]
   | Trolls 3 - Tutti insieme               [ Movie     ][ 6.6 ][ 2023-12-12 ]

[?] Select a season: 1
 > 1

[?] Select an episode: 3. Assedio
   1. Sangue nero
   2. Condizioni
 > 3. Assedio
   4. Bottino di guerra
   5. Braccato
   6. Battaglia sulla spiaggia
   7. Dodici giorni
   8. Offerta

[?] Seleziona la qualità desiderata: 720p
 > 720p
   480p

[?] Cosa vuoi fare:
 > [X] download
   [ ] watch

  0%|                                                                                                                                                                                  | 0/882 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main\main.py", line 287, in <module>
    main()
  File "C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main\main.py", line 285, in main
    actions_map.get(tuple(sorted(action)), lambda: None)()
  File "C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main\main.py", line 147, in <lambda>
    (0,): lambda: perform_download(media, quality_index),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main\main.py", line 160, in perform_download
    VideoDownloader().download(download_options)
  File "C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main\src\downloader.py", line 87, in download
    ts_files = list(tqdm(executor.map(self.download_and_decrypt, urls), total=len(urls)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Novelli\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main\src\downloader.py", line 53, in download_and_decrypt
    self.video_decoder.decrypt_ts_file(temp_filename, f"dec_temp_ts/{output_filename}")
  File "C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main\src\downloader.py", line 16, in decrypt_ts_file
    with open(input_filename, 'rb') as infile, open(output_filename, 'wb') as outfile:
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dec_temp_ts/0000-0075.ts'
PS C:\Users\Novelli\Downloads\stream-buddy-main (2)\stream-buddy-main>

**Comment by Bbalduzz** [comment]
ciao! tutto aggiornato e sistemato

**Comment by artifix100** [comment]
ciao grazie mille ho scaricato l'aggiornamento e mi da il seguente errore : 

PS C:\Users\piern\Downloads\stream-buddy-main (2)\stream-buddy-main> python main.py
Traceback (most recent call last):
  File "C:\Users\piern\Downloads\stream-buddy-main (2)\stream-buddy-main\main.py", line 3, in <module>
    import m3u8_To_MP4
ModuleNotFoundError: No module named 'm3u8_To_MP4'
PS C:\Users\piern\Downloads\stream-buddy-main (2)\stream-buddy-main>

**Comment by artifix100** [comment]
però c'è un altro problema: dopo congiungimento tracce video ed audio l'audio scivola fuori sincrono man mano che passa il tempo del file
